### ISSUE TITLE
메인 -> 다른 탭 -> 메인 이동 시 화면이 위쪽으로 이동됨

### ISSUE THREAD

**Issue by HeoJiin** [Nexters/18th-FS-iOS#42]
![IMG_0603](https://user-images.githubusercontent.com/88474655/143060752-467efbad-e5a3-406c-a619-af0e29abd4fc.PNG)

라벨링 화면이 처음에는 정상이었는데, 다른 탭 갔다가 오니까 위쪽으로 이동되어있는것 같아요.

**Comment by freemjstudio** [comment]
1.3에서 버그 해결했습니다!!
